import 'dart:async';

import 'package:app_links/app_links.dart';
import 'package:captain/core/router/app_router.dart';
import 'package:captain/features/collaboration/application/pending_collab_join_provider.dart';
import 'package:captain/features/export/data/board_state_codec.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Handles inbound `captainapp://` and `captain://` links generated by export/collab.
class DeepLinkListener extends ConsumerStatefulWidget {
  const DeepLinkListener({super.key, required this.child});

  final Widget? child;

  @override
  ConsumerState<DeepLinkListener> createState() => _DeepLinkListenerState();
}

class _DeepLinkListenerState extends ConsumerState<DeepLinkListener> {
  final _codec = const BoardStateCodec();
  StreamSubscription<Uri>? _subscription;
  late final AppLinks _appLinks;

  @override
  void initState() {
    super.initState();
    _appLinks = AppLinks();
    _listenForLinks();
  }

  Future<void> _listenForLinks() async {
    try {
      final initial = await _appLinks.getInitialLink();
      if (initial != null) {
        WidgetsBinding.instance.addPostFrameCallback((_) => _handleUri(initial));
      }
    } catch (_) {
      // Deep links are optional on unsupported platforms.
    }

    _subscription = _appLinks.uriLinkStream.listen(
      _handleUri,
      onError: (_) {},
    );
  }

  void _handleUri(Uri uri) {
    if (uri.scheme == 'captainapp' && uri.host == 'board') {
      final template = _codec.decodeShareLink(uri.toString());
      if (template != null) {
        appRouter.push(AppRoutes.tacticalBoard, extra: template);
      }
      return;
    }

    if (uri.scheme == 'captain' &&
        uri.host == 'collab' &&
        uri.pathSegments.isNotEmpty) {
      final code = uri.pathSegments.first;
      ref.read(pendingCollabJoinCodeProvider.notifier).state = code;
      appRouter.push(AppRoutes.tacticalBoard);
    }
  }

  @override
  void dispose() {
    unawaited(_subscription?.cancel());
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return widget.child ?? const SizedBox.shrink();
  }
}
